# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5471bd7fd9e396ca8de010a3ca94ce1c5a40d3a7328ae6e432b7c4e0a9c22df53542448b3ba22877f0de1efe069d8b775851653c7ce74ee10afd238bca703db9

test:
  secret_key_base: 22af6b957cdc7a4f4e5a9a8729c39666d86e772de50cde164879a4fb702a7de3ffc3fef23030f9941967fc858580a5761586f72ed8df060022e41244b353fe98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
